---
title: "learnitdashboard_1"
output: html_document
---

Fichier de notes du jour 1 de mon travail de TFE. Lundi 09 mai 2022. Présentiel.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Je vais commencer à mettre en place mon projet de TFE. \

Mise en place de différents éléments pour faire fonctionner mon package learnitdashboard. \


J'ai réalisé les opérations du fichier dev2 et j'ai créé mon fichier package learnitdashboard. \

J'ai tenté de faire mon build R CMD check, mais j'avais des problèmes: rtools à installer et d'autres packages. \

Mon package semble prêt à être développé. \


Mise en place de ma dashboard. \

Test de récupération de l'URL par communication depuis le serveur. \

Mise en place d'un module. \


J'ai réussis à faire un sélecteur de panel dans le sidebar de la Dashboard \
J'ai mis en place différents tableaux dans ma Dashboard \
J'ai mis un premier affichage des données de MongoDB avec les 10 premières entrées de h5p, learnr et shiny \
J'ai réussis à personnaliser ces tableaux \

